### ISSUE TITLE
コンフィグが環境と合わない？

### ISSUE THREAD

**Issue by craftpaperbag** [born-in-makuhari/titor#2]
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Library/Python/2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/Library/Python/2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 45, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/Library/Python/2.7/site-packages/django/utils/module_loading.py", line 31, in import_by_path
    error_prefix, module_path, class_name))
ImproperlyConfigured: Module "django.contrib.auth.middleware" does not define a "SessionAuthenticationMiddleware" attribute/class
```

```
$ python --version
Python 2.7.10

$ django-admin.py version
1.6.5
```

**Comment by craftpaperbag** [comment]
うごいた

```
$ python --version
Python 2.7.10
$ django-admin --version
1.9.7
```

```
*   b7256fe (HEAD -> master, origin/master, origin/HEAD) Merge branch 'master' of https://github.com/born-in-makuhari/titor into temp1
|\  
| * a0cce47 Initial commit
* 310d6d5 first commit
```
